#!/usr/bin/env python3
"""Genre configuration: large scene pools + image style + music mode + camera feel."""

NATURE_STYLE = ", cinematic nature photography, epic landscape, volumetric light, ultra detailed, 8k, serene, awe-inspiring, professional color grading"
NATURE_NEG = "people, person, human, text, watermark, logo, cartoon, anime, blurry, lowres, oversaturated, deformed, frame, border"
HORROR_STYLE = ", cinematic horror film still, eerie, unsettling, ominous, volumetric fog, dramatic low key lighting, desaturated cold palette, dread, highly detailed, 8k, anamorphic, film grain"
HORROR_NEG = "text, watermark, logo, cartoon, anime, cute, cheerful, bright, colorful, saturated, deformed, extra limbs, blurry, lowres, frame, border, people faces"

NATURE_POOL = [
    "misty pine forest at dawn, sun rays breaking through fog",
    "still alpine lake mirroring snow-capped mountains at sunrise",
    "powerful waterfall in a lush green canyon, mist rising",
    "golden autumn birch forest, fallen leaves, soft light",
    "dramatic ocean cliffs with crashing waves at golden hour",
    "red rock desert canyon glowing at sunset, deep shadows",
    "aurora borealis over a snowy spruce forest at night",
    "wildflower alpine meadow beneath towering peaks, summer",
    "wide river winding through a green mountain valley, aerial",
    "rugged rocky coastline with turquoise waves and sea foam",
    "sunbeams streaming through a towering redwood grove",
    "snow-covered mountain summit under a clear cold blue sky",
    "endless purple lavender field rolling to the horizon at dusk",
    "foggy lake at sunrise, silhouetted reeds, pink sky reflection",
    "quiet bamboo forest with soft dappled green light",
    "emerald river cutting through a deep slot canyon",
    "tropical jungle waterfall into a clear blue plunge pool",
    "golden savanna grassland under vast dramatic clouds",
    "blue glacier ice cave glowing from within",
    "coastal tide pools at sunset reflecting orange sky",
    "cherry blossom trees along a gentle mountain stream",
    "milky way galaxy arching over jagged silhouetted peaks",
    "rolling emerald green hills under scattered clouds",
    "dramatic storm clouds and lightning over open prairie",
    "tranquil zen pond with lily pads and morning mist",
    "moss-covered rainforest creek with smooth stones",
    "windswept sand dunes at golden hour, rippling ridgelines",
    "frozen waterfall and icicles in a blue winter gorge",
    "sunset over a calm fjord between steep green cliffs",
    "field of tall grass glowing backlit at golden hour",
    "terraced rice fields at dawn wrapped in mist",
    "a lone oak on a rolling hill under a dramatic sky",
    "turquoise glacial lake ringed by pine and granite",
    "autumn maple canopy over a red wooden footbridge",
    "vast salt flats mirroring a pastel twilight sky",
    "a waterfall plunging into a mossy emerald grotto",
    "snowy pine forest under soft falling snow at blue hour",
    "sea stacks in ocean fog at sunrise, long exposure",
    "a meadow of golden wheat rippling in the wind",
    "canyon river bend seen from a high desert overlook",
    "alpine tarn reflecting pink alpenglow on the peaks",
    "a misty valley of rolling tea plantations at dawn",
    "ancient mossy forest with ferns and shafts of light",
    "a calm beach with bioluminescent waves under stars",
    "rolling fog pouring over a green coastal mountain ridge",
]

HORROR_POOL = [
    "a vast derelict alien monolith looming in a fog-choked wasteland at dusk",
    "a dead petrified forest under a blood-red sky, twisted black branches",
    "an abandoned cathedral interior swallowed by mist, shafts of sickly light",
    "a colossal eldritch structure emerging from a black storm-wracked ocean",
    "a bioluminescent cave lined with countless faintly glowing eyes in the dark",
    "a cracked salt desert stretching to a monolithic obelisk under a huge alien moon",
    "a flooded ruined city street, half-submerged, silhouettes standing motionless in fog",
    "a writhing mass of shadow tendrils rising from a chasm of dim red light",
    "an endless corridor of rusted metal, flickering lights, something wrong in the distance",
    "a frozen tundra with a towering black spire and a swirling green aurora of dread",
    "a decaying overgrown asylum ward, peeling walls, a single tipped wheelchair in fog",
    "a swarm of black winged silhouettes blotting out a pale sickly sun",
    "an alien swamp of pulsing organic pods under a churning violet sky",
    "a cavern with an immense fossilized skeleton of an unknown leviathan",
    "a lighthouse on jagged rocks stabbing at a boiling black sea, storm and lightning",
    "a field of pale withered stalks under thick low fog, a distant humanoid shape",
    "a subterranean lake of ink reflecting a hanging inverted city of bone",
    "a shattered moon bleeding light over a scorched obsidian mountain range",
    "a narrow canyon of flesh-like red rock walls, mist pooling in the depths",
    "an abandoned carnival at night, broken carousel, fog rolling through empty stalls",
    "a colossal eye opening within a swirling nebula above a dead planet",
    "a drowned forest, dead trees rising from still black water, thick mist",
    "an ancient stone circle on a moor at night, ground fog, unnatural glow at the center",
    "a derelict spacecraft interior overtaken by dark organic growth, dripping shadows",
    "a mountainside of countless pale standing figures facing away into the fog",
    "a rift in the sky tearing open over a ruined skyline, cold light pouring out",
    "an underground tunnel ending in a wall of writhing darkness and faint teeth",
    "a vast hall of hanging chrysalis pods glistening in dim red emergency light",
    "a barren shore of black sand under twin dying suns, a beached alien colossus",
    "a foggy graveyard of tilted monoliths stretching beyond sight, faint blue mist",
    "a rotting pier stretching into a black sea beneath a sky of dead stars",
    "a ruined temple half-consumed by a pulsing red crystalline growth",
    "an abandoned hospital corridor flooded ankle-deep, fog and flickering light",
    "a colossal hand of stone rising from a fog-drowned bog at twilight",
    "a spiral staircase descending endlessly into red-lit darkness",
    "a dead city of black towers under a churning green sky",
    "a frozen sea with a vast dark shape trapped beneath cracking ice",
    "a forest of pale bone-white trees under a starless void",
    "a cathedral of alien ribs arching over a lake of tar",
    "an empty desert highway vanishing into an approaching wall of black fog",
    "a derelict observatory dome open to a bleeding aurora and wrong constellations",
    "a cavern mouth ringed with monolithic teeth exhaling cold mist",
    "a swamp shrine draped in tattered shrouds under a sick yellow moon",
    "a ruined factory of rusted machinery bleeding shadow into red pools",
    "a vast field of black monoliths humming under a fractured violet sky",
]

GENRES = {
    'nature': {
        'pool': NATURE_POOL, 'style': NATURE_STYLE, 'neg': NATURE_NEG,
        'cfg': 5.0, 'music': 'orchestral', 'xfade_kind': 'fade', 'motion': 'gentle',
        'label': 'nature-orchestral',
    },
    'horror': {
        'pool': HORROR_POOL, 'style': HORROR_STYLE, 'neg': HORROR_NEG,
        'cfg': 5.5, 'music': 'horror', 'xfade_kind': 'fadeblack', 'motion': 'creep',
        'label': 'alien-horror',
    },
}
